services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ["setFramework", ["@contao.framework"]]
        Symfony\Component\DependencyInjection\ContainerAwareInterface:
            calls:
                - ["setContainer", ["@service_container"]] 
    Memo\ImageUsageBundle\Indexer\ImageUsageIndexer:
        tags:
          - { name: 'contao.search_indexer' }
    memo.image.resizer:
        class: Memo\ImageUsageBundle\Image\ImageResizeLogger
        decorates: contao.image.resizer
        arguments: ['@memo.image.resizer.inner']
        public: true
    memo.imageusage.toolbox:
        class: Memo\ImageUsageBundle\Service\Toolbox
        public: true