services:
    Memo\ImageUsageBundle\Indexer\ImageUsageIndexer:
        tags:
          - { name: 'contao.search_indexer' }
    memo.image.resizer:
        class: Memo\ImageUsageBundle\Image\ImageResizeLogger
        decorates: contao.image.resizer
        arguments: ['@memo.image.resizer.inner']
        public: true