services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ["setFramework", ["@contao.framework"]]
        Symfony\Component\DependencyInjection\ContainerAwareInterface:
            calls:
                - ["setContainer", ["@service_container"]]
    mod_imageusage.hook_listener:
        class: Memo\ImageUsageBundle\Service\HookListener
    Memo\ImageUsageBundle\Indexer\ImageUsageIndexer:
        tags:
          - { name: 'contao.search_indexer' }
